const data2 = {
  name: "Pranesh Kumar",
  professionalSummary: [
    "Seasoned professional with a strong background in strategy and investment banking.",
    "Excels in creating innovative products and solutions, driving business growth, and providing strategic advisory services to investors.",
    "Expertise spans corporate finance, bonds, equity, private equity, and venture capital.",
    "Proven track record of managing large, structured transactions and supporting business development activities.",
    "Demonstrated expertise in strategic planning, market analysis, risk assessment, and delivering tailored financial advice.",
    "Strong background in managing client exposures and risks, delivering market analysis reports, and providing consultations.",
    "Skilled in improving workflow processes, enhancing project outcomes through strategic insights, and performance analysis.",
    "Adept at developing annual performance reports, identifying program improvement opportunities, and ensuring clear stakeholder communication.",
    "Proficient in converting complex data into visual presentations to facilitate informed decision-making and enhance project transparency.",
    "Expertise in managing, building, and developing high-performing project teams, coupled with strategic financial insights.",
    "Proactive, detail-oriented, and possesses excellent time management, stakeholder engagement, and communication skills.",
  ],
  technicalSkills: {
    Languages: [],
    Frontend: [],
    Backend: [],
    Framework: [],
    DevOps: [],
    Communications: [
      "Conflict resolution",
      "Business communication",
      "Reporting and Stakeholder Management",
    ],
    Others: [
      "Google Workspace",
      "Microsoft Office",
      "Salesforce",
      "Bloomberg Terminal",
      "Google Analytics",
      "Tableau",
      "Power BI",
      "Refinitiv",
      "Morning Star",
      "Salesforce",
      "Capital IQ",
      "PitchBook",
      "Factiva",
      "Yahoo Finance",
      "OneSource",
      "Preqin",
      "Tracxn",
      "Hoovers",
      "Investment Analysis",
      "Market research and analysis",
      "Sales report analysis",
      "Time Management",
      "Problem-solving",
      "Process Improvement",
      "Multi-tasking",
      "Attention to detail",
      "Data Migration",
      "Business Valuation",
      "Strategic Planning",
      "Risk Management",
      "Business Development",
      "Due Diligence",
      "Financial Reporting",
      "Data Analysis",
    ],
  },
  workExperience: [],
  projects: [
    {
      project: "Project # 1",
      Client: "Vlink Inc.",
      role: null,
      duration: "10 Months",
      description: null,
      ToolsUsed: [],
      responsibilities: [Array],
    },
    {
      project: "Project # 2",
      Client: null,
      role: null,
      duration: "24 Months",
      description: null,
      ToolsUsed: [],
      responsibilities: [Array],
    },
    {
      project: "Project # 3",
      Client: null,
      role: null,
      duration: "26 Months",
      description: null,
      ToolsUsed: [],
      responsibilities: [Array],
    },
    {
      project: "Project # 4",
      Client: null,
      role: null,
      duration: "15 Months",
      description: null,
      ToolsUsed: [],
      responsibilities: [Array],
    },
    {
      project: "Project # 5",
      Client: null,
      role: null,
      duration: "20 Months",
      description: null,
      ToolsUsed: [],
      responsibilities: [Array],
    },
  ],
  education: [
    {
      degree: "MSc in Investment Banking",
      institution: "Queen Mary, University of London",
      location: null,
      year: null,
    },
    {
      degree: "MBA in Finance and Marketing",
      institution: "Welingkar Institute of Management Development and Research",
      location: null,
      year: null,
    },
  ],
  certifications: [
    { name: "Green Belt in Lean Six Sigma", issuer: null, date: null },
  ],
};